Add example GNSS driver launch file
esa-prl/marta_launch pull request #9
Opened 2020-08-20 14:01 UTC by mvoellmy

Propose to place this launch file here until we create a dedicated drivers launch file.

2020-08-24 16:31 UTC, wieset requested changes

2020-08-24 16:31 UTC, wieset commented on launch/gnss_driver.launch.py
> +        SetEnvironmentVariable('RCUTILS_LOGGING_BUFFERED_STREAM', '1'),
This does not do what the comment says. See https://index.ros.org/doc/ros2/Tutorials/Logging-and-logger-configuration/

Since foxy, all log output goes to unbuffered stderr. This env var changes that to buffered output, which can improve performance slighty, but can delay the output. I think we should stick to the default here.

```suggestion
		# Set env var to print messages to stdout immediately
        SetEnvironmentVariable('RCUTILS_LOGGING_BUFFERED_STREAM', '1'),
```

2020-08-24 16:32 UTC, wieset commented
All good otherwise!

2020-08-25 08:26 UTC, mvoellmy commented on launch/gnss_driver.launch.py
> +        SetEnvironmentVariable('RCUTILS_LOGGING_BUFFERED_STREAM', '1'),
Nicely spotted!
I assume your commit suggestion (currently it suggests leaving it how it is) is to remove the the command? 

I guess we should then change that in all launch file. The performance loss should not be too big, since even our main launch files, don't print data continuously.
What do you think?

2020-08-25 08:50 UTC, wieset commented on launch/gnss_driver.launch.py
> +        SetEnvironmentVariable('RCUTILS_LOGGING_BUFFERED_STREAM', '1'),
Ah damn, yeah that was supposed to be my suggestion :D

I think the more we stick to the defaults, the better. You got this from navigation2, right? Is there any mention why they put this?

2020-08-25 08:57 UTC, mvoellmy commented on launch/gnss_driver.launch.py
> +        SetEnvironmentVariable('RCUTILS_LOGGING_BUFFERED_STREAM', '1'),
Yeah, I investigated it today and saw that it was just a PR from someone that changed it mainly to get rid of a warning message.

https://github.com/ros-planning/navigation2/issues/1865

Imo. it's fine to remove it since it's good to use defaults, it keeps it clean and our rovers have high performance PCs.

2020-08-25 09:54 UTC, mvoellmy commented
Changed all launch files to output directly to stderr instead of buffered.

2020-08-25 09:55 UTC, merged